### ISSUE TITLE
Support for PSUBSCRIBE/PUNSUBSCRIBE

### ISSUE THREAD

**Issue by giacomocariello** [azuqua/fred.rs#56]
Would you consider adding support for PSUBSCRIBE/PUNSUBSCRIBE commands?

Details at: https://redis.io/topics/pubsub

**Comment by alecembke-okta** [comment]
Sure that's not a problem. I can probably find time to add that in the next week or so if that works for you.

**Comment by aembke** [comment]
Sure that's not a problem. I can probably find time to add that in the next week or so if that timeline works for you.

**Comment by alecembke-okta** [comment]
This is in master currently and will be 1.1.0 on crates.io
