### ISSUE TITLE
Migrate from tokio-core to tokio.

### ISSUE THREAD

**Issue by singulared** [azuqua/fred.rs#63]
Hello!
As i understand [tokio-core](https://github.com/tokio-rs/tokio-core) are deprecated in favor of tokio.
At this moment i can't integrate tokio-core libraries into tokio based frameworks, like actix.
Did you have a plans for migration to tokio from tokio-core?

**Comment by aembke** [comment]
Yeah that is the plan, but I'm probably a few weeks out from having the time to start that. My goal is to be up to date with the latest tokio ecosystem by November though.

**Comment by perfectmak** [comment]
Hi, I this library and I want to use in a side project of mine. Have you started working on the update to tokio? I could also help work on this if you are quite busy at the moment.

**Comment by aembke** [comment]
hey @perfectmak, I haven't had a chance to get started on this yet with the geo* and lua features that were requested. I'm still shooting to start it this month but you're welcome to work on it as well.

**Comment by alecembke-okta** [comment]
@perfectmak  just a heads up - this repository is moving to a new location [here](https://github.com/aembke/fred.rs). the crates.io location will not change, so you don't need to change anything in your toml if you're using that. i'll put a notice up in the README here sometime soon as well. 

the new version (3.0.0) is a complete rewrite on async/await, new tokio, etc.
