### ISSUE TITLE
GEO related commands

### ISSUE THREAD

**Issue by SharksT** [azuqua/fred.rs#66]
Hello, I can see that there is not GEO related commands implemented, such as GEOADD, GEODIST and so on.

I need those to my use-case, can you help? It is hard to implement?

**Comment by aembke** [comment]
Those should be pretty quick to implement. I was planning on working on this a bit this weekend and I'll add those as well.

**Comment by SharksT** [comment]
Awesome !

**Comment by SharksT** [comment]
Hi, did you manage to do it ?

**Comment by aembke** [comment]
Yeah it's partially implemented on that branch, but I haven't had a chance to fully finish it or add tests yet. I'm planning on finishing it this weekend though.

**Comment by SharksT** [comment]
Any news?

**Comment by alecembke-okta** [comment]
hey @SharksT sorry for the delay. I have this almost entirely implemented, but it turns out the `georadius` commands require breaking changes to the public interface for types. I'm working on trying to do that as easily as possible, but it will likely take a bit more time.

**Comment by SharksT** [comment]
I'm using fred in my project that is going to release its MVP soon, do you think that it can be done in less than a month?,

**Comment by aembke** [comment]
yeah it'll be done by then

**Comment by alecembke-okta** [comment]
@SharksT this will go up in v1.3.0 in this PR https://github.com/azuqua/fred.rs/pull/69 if you want to track it

**Comment by alecembke-okta** [comment]
@SharksT just a heads up - this repository is moving to a new location [here](https://github.com/aembke/fred.rs). the crates.io location will not change, so you don't need to change anything in your toml if you're using that. i'll put a notice up in the README here sometime soon as well. 

the new version (3.0.0) is a complete rewrite on async/await, new tokio, etc, and supports the GEO interface.
