### ISSUE TITLE
Support for evaluate scripts

### ISSUE THREAD

**Issue by RicoGit** [azuqua/fred.rs#68]
Are there any plans for supporting commands EVAL/EVALSHA?

**Comment by aembke** [comment]
Yeah that's in the same branch as the geo commands from https://github.com/azuqua/fred.rs/issues/66. They're already implemented and just need testing at this point, and they should be in the next release sometime next week.

**Comment by RicoGit** [comment]
That's great! Thank you!

**Comment by alecembke-okta** [comment]
@RicoGit this will go up in v1.3.0 this week in this PR https://github.com/azuqua/fred.rs/pull/69 if you want to track it

**Comment by alecembke-okta** [comment]
@RicoGit just a heads up - this repository is moving to a new location [here](https://github.com/aembke/fred.rs). the crates.io location will not change, so you don't need to change anything in your toml if you're using that. i'll put a notice up in the README here sometime soon as well. 

the new version (3.0.0) supports all the lua commands
