### ISSUE TITLE
Support async/await in redis cluster

### ISSUE THREAD

**Issue by ishanbtr** [azuqua/fred.rs#70]
Instead of returning future , its good to achieve the things via async and await.

**Comment by alecembke-okta** [comment]
@ishanbtr  just a heads up - this repository is moving to a new location [here](https://github.com/aembke/fred.rs). the crates.io location will not change, so you don't need to change anything in your toml if you're using that. i'll put a notice up in the README here sometime soon as well. 

the new version (3.0.0) is a complete rewrite on async/await, new tokio, etc.
