### ISSUE TITLE
Support for pipelining

### ISSUE THREAD

**Issue by rohitjoshi** [azuqua/fred.rs#77]
Does it support pipeline more when connected to multi-shard cluster?

**Comment by alecembke-okta** [comment]
@rohitjoshi just a heads up - this repository is moving to a new location [here](https://github.com/aembke/fred.rs). the crates.io location will not change, so you don't need to change anything in your toml if you're using that. i'll put a notice up in the README here sometime soon as well. 

the new version (3.0.0) is a complete rewrite on async/await, new tokio, etc. it also supports automatic pipelining via some configuration settings.
