### ISSUE TITLE
Implement `Error` trait for `RedisError`

### ISSUE THREAD

**Issue by zakcutner** [azuqua/fred.rs#86]
Hi! Thanks for creating this library, it has a really nice interface. I was wondering whether it would be possible to implement the `std::error::Error` trait for `RedisError`? This would mean that the `?` operator could be used in functions returning `Result<T, Box<dyn Error>>`.

**Comment by alecembke-okta** [comment]
@zakcutner just a heads up - this repository is moving to a new location [here](https://github.com/aembke/fred.rs). the crates.io location will not change, so you don't need to change anything in your toml if you're using that. i'll put a notice up in the README here sometime soon as well. 

the latest release (3.0.0) is a complete rewrite on async/await, new tokio, etc. it also adds the `Error` trait to the `RedisError` struct.
